table bellabeat_analysis_dataset
	lineageTag: 354e0140-2387-4181-9f5c-d3c216e3ddf3

	column user_id
		dataType: string
		lineageTag: 0923028a-c5f5-4d7d-94f1-866b60e7ac14
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column activity_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a919425-4420-4b59-a630-da9ca693a727
		summarizeBy: none
		sourceColumn: activity_date

		variation Variación
			isDefault
			relationship: 1911bf4b-95b3-4ca4-b6d4-bae248d07d41
			defaultHierarchy: LocalDateTable_89669211-9951-41e6-906c-2a100f7df40a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column total_steps
		dataType: int64
		formatString: 0
		lineageTag: 808ec19d-d321-43cc-ad88-dac934cd86cf
		summarizeBy: sum
		sourceColumn: total_steps

		annotation SummarizationSetBy = Automatic

	column total_distance
		dataType: double
		lineageTag: 12763439-81d1-4852-9e2d-f2f2d9e5caa7
		summarizeBy: sum
		sourceColumn: total_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tracker_distance
		dataType: double
		lineageTag: d5cc959f-123f-4d0c-ae3a-05e1d98f10b5
		summarizeBy: sum
		sourceColumn: tracker_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column logged_activities_distance
		dataType: double
		lineageTag: 801d091b-5356-42e0-ba3b-3fe57d34956d
		summarizeBy: sum
		sourceColumn: logged_activities_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column very_active_distance
		dataType: double
		lineageTag: fc0ffa94-33c0-4880-97e3-b86350f01026
		summarizeBy: sum
		sourceColumn: very_active_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column moderately_active_distance
		dataType: double
		lineageTag: 59d40b6c-4de8-45c2-b5a2-b064231307e8
		summarizeBy: sum
		sourceColumn: moderately_active_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column light_active_distance
		dataType: double
		lineageTag: f31a6430-f5dd-440a-bcc7-188db1d02af5
		summarizeBy: sum
		sourceColumn: light_active_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sedentary_active_distance
		dataType: double
		lineageTag: 978ca40d-7700-4f57-af5b-d1b29b95d50d
		summarizeBy: sum
		sourceColumn: sedentary_active_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column very_active_minutes
		dataType: int64
		formatString: 0
		lineageTag: 0daba368-ae67-4b6a-b7f9-e056e023ff04
		summarizeBy: sum
		sourceColumn: very_active_minutes

		annotation SummarizationSetBy = Automatic

	column fairly_active_minutes
		dataType: int64
		formatString: 0
		lineageTag: 496987ee-8e07-4df4-b325-168afb43355e
		summarizeBy: sum
		sourceColumn: fairly_active_minutes

		annotation SummarizationSetBy = Automatic

	column lightly_active_minutes
		dataType: int64
		formatString: 0
		lineageTag: cdf8dbdd-0db9-45d2-94c5-6511697e629a
		summarizeBy: sum
		sourceColumn: lightly_active_minutes

		annotation SummarizationSetBy = Automatic

	column sedentary_minutes
		dataType: int64
		formatString: 0
		lineageTag: 3e7116e8-2318-4b82-8e19-64300446f263
		summarizeBy: sum
		sourceColumn: sedentary_minutes

		annotation SummarizationSetBy = Automatic

	column calories
		dataType: int64
		formatString: 0
		lineageTag: f0f00f84-e76e-40c8-a098-7daf1da0bd59
		summarizeBy: sum
		sourceColumn: calories

		annotation SummarizationSetBy = Automatic

	column source_period
		dataType: string
		lineageTag: 7851c34e-c6b3-435c-88b9-c264b3eb5fcf
		summarizeBy: none
		sourceColumn: source_period

		annotation SummarizationSetBy = Automatic

	column source_file
		dataType: string
		lineageTag: 6cdba248-07f1-45a7-bdce-de3d326e2add
		summarizeBy: none
		sourceColumn: source_file

		annotation SummarizationSetBy = Automatic

	column active_minutes
		dataType: int64
		formatString: 0
		lineageTag: 98f523bf-8231-4891-a2de-8246cbd67afc
		summarizeBy: sum
		sourceColumn: active_minutes

		annotation SummarizationSetBy = Automatic

	column tracked_minutes
		dataType: int64
		formatString: 0
		lineageTag: 63a1a194-2409-453a-84d7-af4f96349eb2
		summarizeBy: sum
		sourceColumn: tracked_minutes

		annotation SummarizationSetBy = Automatic

	column sedentary_ratio
		dataType: double
		formatString: 0
		lineageTag: 183ce34e-9ef2-40f7-9bd5-31e872fbf7fb
		summarizeBy: sum
		sourceColumn: sedentary_ratio

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: string
		lineageTag: 9d758914-c6a5-4c28-b474-346bc97ae089
		summarizeBy: none
		sourceColumn: day_of_week
		sortByColumn: day_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_order
		dataType: int64
		formatString: 0
		lineageTag: 9d129e1e-c04c-4061-867f-a6dc03446df4
		summarizeBy: sum
		sourceColumn: day_order

		annotation SummarizationSetBy = Automatic

	column activity_level
		dataType: string
		lineageTag: 34f3fa02-6bca-4880-8cb2-dc1121611b0f
		summarizeBy: none
		sourceColumn: activity_level

		annotation SummarizationSetBy = Automatic

	column meets_10000_steps
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f49a7d74-e859-4f0f-b40c-fd5b80a1600f
		summarizeBy: none
		sourceColumn: meets_10000_steps

		annotation SummarizationSetBy = Automatic

	column total_sleep_records
		dataType: int64
		formatString: 0
		lineageTag: 2c927f2f-ac97-40a4-9d74-f336b1c6c89b
		summarizeBy: sum
		sourceColumn: total_sleep_records

		annotation SummarizationSetBy = Automatic

	column total_minutes_asleep
		dataType: int64
		formatString: 0
		lineageTag: a339e959-c5b8-43be-84d7-82fbc92397a3
		summarizeBy: sum
		sourceColumn: total_minutes_asleep

		annotation SummarizationSetBy = Automatic

	column total_time_in_bed
		dataType: int64
		formatString: 0
		lineageTag: 99fc15c2-199b-4e4d-bc29-8e927c878d2d
		summarizeBy: sum
		sourceColumn: total_time_in_bed

		annotation SummarizationSetBy = Automatic

	column sleep_hours
		dataType: double
		formatString: 0
		lineageTag: 3d7d037a-8d96-4f33-9afe-5e46975013c4
		summarizeBy: sum
		sourceColumn: sleep_hours

		annotation SummarizationSetBy = Automatic

	column time_in_bed_hours
		dataType: double
		formatString: 0
		lineageTag: c29ff443-aff0-4039-99d4-c43d8c8ee516
		summarizeBy: sum
		sourceColumn: time_in_bed_hours

		annotation SummarizationSetBy = Automatic

	column sleep_efficiency
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: 4137d585-ec3f-43aa-9d79-6947d1914f04
		summarizeBy: sum
		sourceColumn: sleep_efficiency

		annotation SummarizationSetBy = Automatic

	column sleep_hours_clean =
			
			VAR SleepValue = bellabeat_analysis_dataset[sleep_hours]
			RETURN
			IF(
			    ISBLANK(SleepValue),
			    BLANK(),
			    IF(
			        SleepValue > 24,
			        DIVIDE(SleepValue, 60),
			        SleepValue
			    )
			)
		lineageTag: 155d024d-d1f2-4086-a8d0-0ebcef56d24c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Registro actividad' = ```
			
			bellabeat_analysis_dataset[user_id] 
			& " - " 
			& FORMAT(bellabeat_analysis_dataset[activity_date], "yyyy-MM-dd")
			```
		lineageTag: f1c9ea5a-a96f-4b3b-9e1e-402515c8e273
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition bellabeat_analysis_dataset = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\genes\Desktop\Ciencia de datos\Caso-de-exito\data\processed\bellabeat_analysis_dataset.csv"), [Delimiter = ",", Columns = 30, Encoding = 65001]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    #"Tipo cambiado con configuración regional5" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"sleep_hours", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional6" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional5", {{"time_in_bed_hours", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional7" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional6", {{"sleep_efficiency", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional8" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional7", {{"sedentary_ratio", type number}}, "en-US"),
				  #"Tipo cambiado con configuración regional4" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional8", {{"sleep_hours", type number}}, "en-US"),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional4",{{"user_id", type text}, {"activity_date", type date}, {"day_of_week", type text}, {"day_order", Int64.Type}, {"activity_level", type text}, {"sleep_hours", type number}, {"sleep_efficiency", type number}}),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Tipo cambiado", {{"sleep_hours", type number}}, "en-US"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional",{{"time_in_bed_hours", type number}}),
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Tipo cambiado1", {{"time_in_bed_hours", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional2" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional1", {{"sleep_efficiency", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional3" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional2", {{"sedentary_ratio", type number}}, "en-US"),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional3",{{"total_steps", Int64.Type}, {"total_distance", type number}, {"tracker_distance", type number}, {"logged_activities_distance", type number}, {"very_active_distance", type number}, {"moderately_active_distance", type number}, {"light_active_distance", type number}, {"sedentary_active_distance", type number}, {"very_active_minutes", Int64.Type}, {"fairly_active_minutes", Int64.Type}, {"lightly_active_minutes", Int64.Type}, {"sedentary_minutes", Int64.Type}, {"calories", Int64.Type}, {"active_minutes", Int64.Type}, {"tracked_minutes", Int64.Type}, {"meets_10000_steps", type logical}, {"total_sleep_records", Int64.Type}, {"total_minutes_asleep", Int64.Type}, {"total_time_in_bed", Int64.Type}})
				in
				  #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

