table user_segments
	lineageTag: d3426f38-d70d-4efd-9d54-079714ed9ea3

	column user_id
		dataType: string
		lineageTag: fa1de9cd-d344-42b1-ab94-35cb311543b4
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column tracked_days
		dataType: int64
		formatString: 0
		lineageTag: 8aa774f6-1f6d-400e-9281-76bd07a4b37b
		summarizeBy: none
		sourceColumn: tracked_days

		annotation SummarizationSetBy = Automatic

	column avg_steps
		dataType: double
		formatString: 0
		lineageTag: 1b8397c0-d21f-4379-b217-d10cb903db5a
		summarizeBy: none
		sourceColumn: avg_steps

		annotation SummarizationSetBy = Automatic

	column avg_calories
		dataType: double
		formatString: 0
		lineageTag: c8f38b19-5920-43a3-9484-b36769bcc706
		summarizeBy: none
		sourceColumn: avg_calories

		annotation SummarizationSetBy = Automatic

	column avg_active_minutes
		dataType: double
		formatString: 0
		lineageTag: 9e40c588-37a7-4e2e-9bc0-0f226fee8511
		summarizeBy: none
		sourceColumn: avg_active_minutes

		annotation SummarizationSetBy = Automatic

	column avg_sedentary_minutes
		dataType: double
		formatString: 0
		lineageTag: dea884db-01b7-48c1-b9bf-fc931eaab0a0
		summarizeBy: none
		sourceColumn: avg_sedentary_minutes

		annotation SummarizationSetBy = Automatic

	column avg_sleep_hours
		dataType: double
		formatString: 0
		lineageTag: 85fe0a2d-515f-4bd2-aa27-2932ddccdf73
		summarizeBy: none
		sourceColumn: avg_sleep_hours

		annotation SummarizationSetBy = Automatic

	column days_meeting_10000_steps
		dataType: int64
		formatString: 0
		lineageTag: aeeb055d-4008-46e1-9aa4-fcfbb215f997
		summarizeBy: none
		sourceColumn: days_meeting_10000_steps

		annotation SummarizationSetBy = Automatic

	column pct_days_meeting_10000_steps
		dataType: double
		formatString: 0
		lineageTag: 1bee81c8-a053-4aa4-90f1-f3a6070f2b8e
		summarizeBy: none
		sourceColumn: pct_days_meeting_10000_steps

		annotation SummarizationSetBy = Automatic

	column user_segment
		dataType: string
		lineageTag: eb13fce9-4a5c-4c0b-9017-d8ee0b26107f
		summarizeBy: none
		sourceColumn: user_segment
		sortByColumn: segment_order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column segment_order
		dataType: int64
		formatString: 0
		lineageTag: eb95d8d9-19b9-4cc4-bda8-ce6485033a5f
		summarizeBy: none
		sourceColumn: segment_order

		annotation SummarizationSetBy = Automatic

	partition user_segments = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\genes\Desktop\Ciencia de datos\Caso-de-exito\data\processed\user_segments.csv"), [Delimiter = ",", Columns = 10, Encoding = 65001]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"user_id", Int64.Type}, {"tracked_days", Int64.Type}, {"avg_steps", Int64.Type}, {"avg_calories", Int64.Type}, {"avg_active_minutes", Int64.Type}, {"avg_sedentary_minutes", Int64.Type}, {"avg_sleep_hours", Int64.Type}, {"days_meeting_10000_steps", Int64.Type}, {"pct_days_meeting_10000_steps", Int64.Type}, {"user_segment", type text}}, "es"),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo de columna cambiado",{{"user_id", type text}, {"user_segment", type text}, {"avg_steps", type number}, {"avg_active_minutes", type number}, {"avg_sleep_hours", type number}, {"pct_days_meeting_10000_steps", type number}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado", "segment_order", each if [user_segment] = "baja_actividad" then 1 else if [user_segment] = "actividad_ligera" then 2 else if [user_segment] = "actividad_media" then 3 else if [user_segment] = "alta_actividad" then 4 else null),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"segment_order", Int64.Type}}),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Tipo cambiado1", {{"avg_sleep_hours", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional", {{"pct_days_meeting_10000_steps", type number}}, "en-US"),
				    #"Tipo cambiado con configuración regional2" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional1", {{"user_id", type text}}, "en-US"),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional2",{{"avg_calories", type number}, {"avg_sedentary_minutes", type number}, {"avg_sleep_hours", type number}})
				in
				  #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

